#!/usr/bin/env node
// Regenerates src/data/* from the read-only Ruby reference clones:
//
//   ../calendarium-romanum/data/*.txt              -> src/data/sanctorale-files.ts
//   ../calendarium-romanum/config/locales/*.yml    -> src/data/locales.ts
//   ../church-calendar-api/config/calendars.yml    -> src/data/calendars-config.ts
//
// CALENDARIUM_ROMANUM_DIR and CHURCH_CALENDAR_API_DIR point at clones elsewhere.
//
// The package has no runtime dependencies: the data is embedded as TypeScript
// modules so the library works in Node, in a webpack browser bundle and in
// Lambda without any filesystem access.
//
// Run with `npm run sync-data`.

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import yaml from 'js-yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = resolve(HERE, '..');
const CR_REPO = resolve(process.env.CALENDARIUM_ROMANUM_DIR ?? join(PKG, '..', 'calendarium-romanum'));
const API_REPO = resolve(process.env.CHURCH_CALENDAR_API_DIR ?? join(PKG, '..', 'church-calendar-api'));
const OUT_DIR = join(PKG, 'src', 'data');

const GENERATED_BY = 'scripts/sync-data.mjs';

function gitSha(repo) {
  try {
    return execFileSync('git', ['-C', repo, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

function header(sources) {
  const lines = [
    `// GENERATED by ${GENERATED_BY} — do not edit`,
    '//',
    '// Sources:',
  ];
  for (const { label, sha } of sources) {
    lines.push(`//   ${label} @ ${sha}`);
  }
  lines.push('');
  return lines.join('\n');
}

/** JSON is a strict subset of TS object-literal syntax, so this is always valid TS. */
function lit(value, indent = 0) {
  return JSON.stringify(value, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : ' '.repeat(indent) + line))
    .join('\n');
}

// ---------------------------------------------------------------- sanctorale

function buildSanctoraleFiles(sha) {
  const dataDir = join(CR_REPO, 'data');
  const names = readdirSync(dataDir)
    .filter((n) => n.endsWith('.txt'))
    .sort();

  const entries = names.map((name) => {
    const siglum = name.replace(/\.txt$/, '');
    // Verbatim file text, including the YAML front matter and the trailing newline.
    const text = readFileSync(join(dataDir, name), 'utf8');
    return `  ${JSON.stringify(siglum)}: ${JSON.stringify(text)},`;
  });

  return [
    header([{ label: 'calendarium-romanum/data/*.txt', sha }]),
    '/** Verbatim contents of the packaged sanctorale data files, keyed by siglum. */',
    'export const SANCTORALE_FILES: Record<string, string> = {',
    ...entries,
    '};',
    '',
    '/** Sigla of all packaged sanctorale data files (alphabetical, i.e. data-directory order). */',
    `export const SANCTORALE_SIGLA: readonly string[] = ${lit(names.map((n) => n.replace(/\.txt$/, '')))};`,
    '',
  ].join('\n');
}

// ------------------------------------------------------------------- locales

function buildLocales(sha) {
  const localesDir = join(CR_REPO, 'config', 'locales');
  const names = readdirSync(localesDir)
    .filter((n) => n.endsWith('.yml'))
    .sort();

  const tables = {};
  const locales = [];
  for (const name of names) {
    const loaded = yaml.load(readFileSync(join(localesDir, name), 'utf8'));
    const keys = Object.keys(loaded);
    if (keys.length !== 1) {
      throw new Error(`${name}: expected exactly one top-level key, got ${keys.join(', ')}`);
    }
    const locale = keys[0];
    locales.push(locale);
    tables[locale] = loaded[locale];
  }

  return [
    header([{ label: 'calendarium-romanum/config/locales/*.yml', sha }]),
    '/** A node of a locale table: either a translated string or a nested sub-table. */',
    'export type LocaleTree = { [key: string]: string | LocaleTree };',
    '',
    '/** Locales shipped by calendarium-romanum (`I18n.available_locales`). */',
    `export const AVAILABLE_LOCALES = ${lit(locales)} as const;`,
    '',
    'export type Locale = (typeof AVAILABLE_LOCALES)[number];',
    '',
    '/** The translation tables, one per locale. */',
    `export const LOCALES: Record<Locale, LocaleTree> = ${lit(tables)};`,
    '',
  ].join('\n');
}

// --------------------------------------------------------- calendars config

function buildCalendarsConfig(sha) {
  const path = join(API_REPO, 'config', 'calendars.yml');
  // js-yaml's default schema resolves anchors/aliases and YAML 1.1 `<<` merge keys,
  // exactly like Ruby's Psych does for church-calendar-api's CalendarRepository.
  const config = yaml.load(readFileSync(path, 'utf8'));
  const keys = Object.keys(config); // insertion order == file order; /calendars returns this order

  const entries = keys.map((key) => ({ key, config: config[key] }));

  return [
    header([{ label: 'church-calendar-api/config/calendars.yml', sha }]),
    '/** One `sanctorale:` layer of a calendar: a packaged siglum or a data file name. */',
    'export interface SanctoraleSource {',
    '  packaged?: string;',
    '  file?: string;',
    '}',
    '',
    '/** A single calendar definition from config/calendars.yml (anchors/merges already resolved). */',
    'export interface CalendarConfig {',
    '  title: string;',
    '  language: string;',
    '  description?: string;',
    '  sanctorale: SanctoraleSource[];',
    '  temporale_extensions?: string[];',
    '  transfer_to_sunday?: string[];',
    '}',
    '',
    'export interface CalendarConfigEntry {',
    '  key: string;',
    '  config: CalendarConfig;',
    '}',
    '',
    '/** Calendar ids in config-file order — `GET /api/v0/:lang/calendars` returns exactly this. */',
    `export const CALENDAR_KEYS: readonly string[] = ${lit(keys)};`,
    '',
    '/** Calendar definitions in config-file order. */',
    `export const CALENDARS_CONFIG: readonly CalendarConfigEntry[] = ${lit(entries)};`,
    '',
    '/** The same definitions keyed by calendar id. */',
    'export const CALENDARS_BY_KEY: Record<string, CalendarConfig> = Object.fromEntries(',
    '  CALENDARS_CONFIG.map((entry) => [entry.key, entry.config]),',
    ');',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------- main

function main() {
  const crSha = gitSha(CR_REPO);
  const apiSha = gitSha(API_REPO);

  mkdirSync(OUT_DIR, { recursive: true });

  const files = {
    'sanctorale-files.ts': buildSanctoraleFiles(crSha),
    'locales.ts': buildLocales(crSha),
    'calendars-config.ts': buildCalendarsConfig(apiSha),
  };

  for (const [name, contents] of Object.entries(files)) {
    writeFileSync(join(OUT_DIR, name), contents, 'utf8');
    process.stdout.write(`wrote src/data/${name} (${contents.length} bytes)\n`);
  }
}

main();
