// GENERATED by scripts/sync-data.mjs — do not edit
//
// Sources:
//   church-calendar-api/config/calendars.yml @ e1ca5c48f41c5a9402385a78d1928a7a5b0a5f81

/** One `sanctorale:` layer of a calendar: a packaged siglum or a data file name. */
export interface SanctoraleSource {
  packaged?: string;
  file?: string;
}

/** A single calendar definition from config/calendars.yml (anchors/merges already resolved). */
export interface CalendarConfig {
  title: string;
  language: string;
  description?: string;
  sanctorale: SanctoraleSource[];
  temporale_extensions?: string[];
  transfer_to_sunday?: string[];
}

export interface CalendarConfigEntry {
  key: string;
  config: CalendarConfig;
}

/** Calendar ids in config-file order — `GET /api/v0/:lang/calendars` returns exactly this. */
export const CALENDAR_KEYS: readonly string[] = [
  "general-en",
  "general-la",
  "general-fr",
  "general-it",
  "general-es",
  "us",
  "us-ascension",
  "us-boston",
  "us-hartford",
  "us-new-york",
  "us-newark",
  "us-omaha",
  "us-philadelphia",
  "czech",
  "czech-cechy",
  "czech-morava",
  "czech-pha",
  "czech-ltm",
  "czech-hk",
  "czech-cb",
  "czech-plz",
  "czech-olm",
  "czech-brn",
  "czech-oo",
  "default"
];

/** Calendar definitions in config-file order. */
export const CALENDARS_CONFIG: readonly CalendarConfigEntry[] = [
  {
    "key": "general-en",
    "config": {
      "title": "General Roman Calendar",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        }
      ]
    }
  },
  {
    "key": "general-la",
    "config": {
      "title": "Calendarium Romanum Generale",
      "language": "la",
      "sanctorale": [
        {
          "packaged": "universal-la"
        }
      ]
    }
  },
  {
    "key": "general-fr",
    "config": {
      "title": "Calendrier Général Romain",
      "language": "fr",
      "sanctorale": [
        {
          "packaged": "universal-fr"
        }
      ]
    }
  },
  {
    "key": "general-it",
    "config": {
      "title": "Calendario Romano Generale",
      "language": "it",
      "sanctorale": [
        {
          "packaged": "universal-it"
        }
      ]
    }
  },
  {
    "key": "general-es",
    "config": {
      "title": "Calendario Romano General",
      "language": "es",
      "sanctorale": [
        {
          "packaged": "universal-es"
        }
      ]
    }
  },
  {
    "key": "us",
    "config": {
      "title": "US Calendar",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "ascension",
        "corpus_christi"
      ]
    }
  },
  {
    "key": "us-ascension",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-boston",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-hartford",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-new-york",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-newark",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-omaha",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "us-philadelphia",
    "config": {
      "title": "US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)",
      "language": "en",
      "sanctorale": [
        {
          "packaged": "universal-en"
        },
        {
          "packaged": "us-en"
        }
      ],
      "temporale_extensions": [
        "ThanksgivingUS"
      ],
      "transfer_to_sunday": [
        "epiphany",
        "corpus_christi"
      ],
      "description": "These Diocese have retained its celebration on the proper Thursday"
    }
  },
  {
    "key": "czech",
    "config": {
      "title": "Český národní kalendář",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-cechy",
    "config": {
      "title": "kalendář české církevní provincie",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-morava",
    "config": {
      "title": "kalendář moravské církevní provincie",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-morava-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-pha",
    "config": {
      "title": "kalendář pražské arcidiecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        },
        {
          "packaged": "czech-praha-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-ltm",
    "config": {
      "title": "kalendář litoměřické diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        },
        {
          "packaged": "czech-litomerice-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-hk",
    "config": {
      "title": "kalendář královéhradecké diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        },
        {
          "packaged": "czech-hradec-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-cb",
    "config": {
      "title": "kalendář českobudějovické diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        },
        {
          "packaged": "czech-budejovice-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-plz",
    "config": {
      "title": "kalendář plzeňské diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-cechy-cs"
        },
        {
          "packaged": "czech-plzen-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-olm",
    "config": {
      "title": "kalendář olomoucké arcidiecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-morava-cs"
        },
        {
          "packaged": "czech-olomouc-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-brn",
    "config": {
      "title": "kalendář brněnské diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-morava-cs"
        },
        {
          "packaged": "czech-brno-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "czech-oo",
    "config": {
      "title": "kalendář ostravsko-opavské diecéze",
      "language": "cs",
      "sanctorale": [
        {
          "packaged": "czech-cs"
        },
        {
          "packaged": "czech-morava-cs"
        },
        {
          "packaged": "czech-ostrava-cs"
        }
      ],
      "temporale_extensions": [
        "ChristEternalPriest"
      ]
    }
  },
  {
    "key": "default",
    "config": {
      "title": "Calendarium Romanum Generale",
      "language": "la",
      "sanctorale": [
        {
          "packaged": "universal-la"
        }
      ]
    }
  }
];

/** The same definitions keyed by calendar id. */
export const CALENDARS_BY_KEY: Record<string, CalendarConfig> = Object.fromEntries(
  CALENDARS_CONFIG.map((entry) => [entry.key, entry.config]),
);
