// GENERATED by scripts/sync-data.mjs — do not edit
//
// Sources:
//   calendarium-romanum/config/locales/*.yml @ 713ebbb818daad5fa40f37f839bdd40ce71109e4

/** A node of a locale table: either a translated string or a nested sub-table. */
export type LocaleTree = { [key: string]: string | LocaleTree };

/** Locales shipped by calendarium-romanum (`I18n.available_locales`). */
export const AVAILABLE_LOCALES = [
  "cs",
  "en",
  "es",
  "fr",
  "it",
  "la"
] as const;

export type Locale = (typeof AVAILABLE_LOCALES)[number];

/** The translation tables, one per locale. */
export const LOCALES: Record<Locale, LocaleTree> = {
  "cs": {
    "temporale": {
      "season": {
        "advent": "Doba adventní",
        "christmas": "Doba vánoční",
        "lent": "Doba postní",
        "easter": "Doba velikonoční",
        "ordinary": "Liturgické mezidobí"
      },
      "solemnity": {
        "nativity": "Narození Páně",
        "holy_family": "Svaté rodiny Ježíše, Marie a Josefa",
        "mother_of_god": "Oktáv Narození Páně. Matky Boží, Panny Marie",
        "epiphany": "Zjevení Páně",
        "baptism_of_lord": "Křtu Páně",
        "ash_wednesday": "Popeleční středa",
        "palm_sunday": "Květná neděle",
        "good_friday": "Velký pátek",
        "holy_saturday": "Bílá sobota",
        "easter_sunday": "Zmrtvýchvstání Páně",
        "ascension": "Nanebevstoupení Páně",
        "pentecost": "Seslání Ducha svatého",
        "holy_trinity": "Nejsvětější Trojice",
        "corpus_christi": "Těla a krve Páně",
        "sacred_heart": "Nejsvětějšího srdce Ježíšova",
        "mother_of_church": "Panny Marie, Matky církve",
        "immaculate_heart": "Neposkvrněného Srdce Panny Marie",
        "christ_king": "Ježíše Krista krále",
        "saturday_memorial_bvm": "Sobotní památka Panny Marie"
      },
      "extension": {
        "christ_eternal_priest": "Ježíše Krista, nejvyššího a věčného kněze"
      },
      "ordinary": {
        "sunday": "%{week} neděle v mezidobí",
        "ferial": "%{weekday} %{week} týdne v mezidobí"
      },
      "advent": {
        "sunday": "%{week} neděle adventní",
        "ferial": "%{weekday} po %{week} neděli adventní",
        "before_christmas": "%{day} prosince"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "%{day} den v oktávu Narození Páně"
        },
        "sunday": "%{week} neděle po Narození Páně",
        "ferial": "%{weekday} po oktávu Narození Páně",
        "after_epiphany": {
          "ferial": "%{weekday} po Zjevení Páně"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} po Popeleční středě"
        },
        "sunday": "%{week} neděle postní",
        "ferial": "%{weekday} po %{week} neděli postní",
        "holy_week": {
          "ferial": "%{weekday} Svatého týdne"
        }
      },
      "easter": {
        "octave": {
          "ferial": "%{weekday} v oktávu velikonočním"
        },
        "sunday": "%{week} neděle velikonoční",
        "ferial": "%{weekday} po %{week} neděli velikonoční"
      }
    },
    "rank": {
      "1_1": "Velikonoční triduum",
      "1_2": "Primární liturgické dny",
      "1_3": "Slavnosti zapsané ve všeobecném kalendáři",
      "1_4": "Vlastní slavnosti",
      "2_5": "Svátky Páně zapsané ve všeobecném kalendáři",
      "2_6": "Neprivilegované neděle",
      "2_7": "Svátky svatých zapsané ve všeobecném kalendáři",
      "2_8": "Vlastní svátky",
      "2_9": "Privilegované ferie",
      "3_10": "Závazné památky všeobecného kalendáře",
      "3_11": "Vlastní závazné památky",
      "3_12": "Nezávazné památky",
      "3_13": "Ferie",
      "4_0": "Připomínky",
      "short": {
        "solemnity": "slavnost",
        "feast": "svátek",
        "sunday": "neděle",
        "memorial": "památka",
        "memorial_opt": "nezávazná památka",
        "ferial": "ferie",
        "commemoration": "připomínka"
      }
    },
    "weekday": {
      "0": "Neděle",
      "1": "Pondělí",
      "2": "Úterý",
      "3": "Středa",
      "4": "Čtvrtek",
      "5": "Pátek",
      "6": "Sobota"
    },
    "colour": {
      "violet": "fialová",
      "white": "bílá",
      "green": "zelená",
      "red": "červená"
    }
  },
  "en": {
    "sanctorale": {
      "solemnity": {
        "baptist_birth_vigil": "The Nativity of Saint John the Baptist: At the Vigil Mass",
        "peter_paul_vigil": "Saints Peter and Paul, Apostles: At the Vigil Mass",
        "assumption_vigil": "The Assumption of the Blessed Virgin Mary: At the Vigil Mass"
      }
    },
    "temporale": {
      "season": {
        "advent": "Advent",
        "christmas": "Christmas Season",
        "lent": "Lent",
        "easter": "Easter Season",
        "ordinary": "Ordinary Time"
      },
      "solemnity": {
        "nativity": "The Nativity of the Lord [CHRISTMAS]",
        "nativity_vigil": "The Nativity of the Lord [CHRISTMAS]: At the Vigil Mass",
        "holy_family": "The Holy Family of Jesus, Mary and Joseph",
        "mother_of_god": "Solemnity of Mary, the Holy Mother of God",
        "epiphany": "The Epiphany of the Lord",
        "epiphany_vigil": "The Epiphany of the Lord: At the Vigil Mass",
        "baptism_of_lord": "The Baptism of the Lord",
        "ash_wednesday": "Ash Wednesday",
        "palm_sunday": "Palm Sunday of the Passion of the Lord",
        "holy_thursday": "Thursday of Holy Week [Holy Thursday]: The Chrism Mass",
        "holy_thursday_evening": "Thursday of the Lord’s Supper: At the Evening Mass",
        "good_friday": "Friday of the Passion of the Lord [Good Friday]",
        "holy_saturday": "Holy Saturday",
        "easter_sunday": "Easter Sunday of the Resurrection of the Lord",
        "easter_sunday_vigil": "Easter Sunday of the Resurrection of the Lord: The Easter Vigil in the Holy Night",
        "ascension": "The Ascension of the Lord",
        "ascension_vigil": "The Ascension of the Lord: At the Vigil Mass",
        "pentecost": "Pentecost Sunday",
        "pentecost_vigil": "Pentecost Sunday: At the Vigil Mass",
        "holy_trinity": "The Most Holy Trinity",
        "corpus_christi": "The Most Holy Body and Blood of Christ (CORPUS CHRISTI)",
        "sacred_heart": "The Most Sacred Heart of Jesus",
        "mother_of_church": "The Blessed Virgin Mary, Mother of the Church",
        "immaculate_heart": "The Immaculate Heart of the Blessed Virgin Mary",
        "christ_king": "Our Lord Jesus Christ, King of the Universe",
        "saturday_memorial_bvm": "Mass for the Blessed Virgin Mary on Saturday"
      },
      "extension": {
        "christ_eternal_priest": "Our Lord Jesus Christ, The Eternal High Priest",
        "thanksgiving": "Thanksgiving Day"
      },
      "ordinary": {
        "sunday": "%{week} Sunday in Ordinary Time",
        "ferial": "%{weekday} of the %{week} Week in Ordinary Time"
      },
      "advent": {
        "sunday": "%{week} Sunday of Advent",
        "ferial": "%{weekday} of the %{week} Week of Advent",
        "before_christmas": "December %{day}"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "%{day} Day within the Octave of the Nativity of the Lord [Christmas]"
        },
        "sunday": "%{week} Sunday after the Nativity [Christmas]",
        "ferial": "%{weekday} of Christmas Time: January %{day}",
        "after_epiphany": {
          "ferial": "%{weekday} after Epiphany",
          "ferial_with_day": "%{weekday} after Epiphany: January %{day}"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} after Ash Wednesday"
        },
        "sunday": "%{week} Sunday of Lent",
        "ferial": "%{weekday} of the %{week} Week of Lent",
        "holy_week": {
          "ferial": "%{weekday} of Holy Week"
        }
      },
      "easter": {
        "octave": {
          "ferial": "%{weekday} Within the Octave of Easter"
        },
        "sunday": "%{week} Sunday of Easter",
        "ferial": "%{weekday} of the %{week} week of Easter"
      }
    },
    "rank": {
      "1_1": "Easter triduum",
      "1_2": "Primary liturgical days",
      "1_3": "Solemnities in the General Calendar",
      "1_4": "Proper solemnities",
      "2_5": "Feasts of the Lord in the General Calendar",
      "2_6": "Unprivileged Sundays",
      "2_7": "Feasts of saints in the General Calendar",
      "2_8": "Proper feasts",
      "2_9": "Privileged ferials",
      "3_10": "Obligatory memorials in the General Calendar",
      "3_11": "Proper obligatory memorials",
      "3_12": "Optional memorials",
      "3_13": "Ferials",
      "4_0": "Commemorations",
      "short": {
        "solemnity": "solemnity",
        "feast": "feast",
        "sunday": "Sunday",
        "memorial": "memorial",
        "memorial_opt": "optional memorial",
        "ferial": "ferial",
        "commemoration": "commemoration"
      }
    },
    "weekday": {
      "0": "Sunday",
      "1": "Monday",
      "2": "Tuesday",
      "3": "Wednesday",
      "4": "Thursday",
      "5": "Friday",
      "6": "Saturday"
    },
    "colour": {
      "violet": "violet",
      "white": "white",
      "green": "green",
      "red": "red"
    }
  },
  "es": {
    "temporale": {
      "season": {
        "advent": "Adviento",
        "christmas": "Navidad",
        "lent": "Cuaresma",
        "easter": "Pascua",
        "ordinary": "Tiempo Ordinario"
      },
      "solemnity": {
        "nativity": "Natividad",
        "holy_family": "La Sagrada Familia",
        "mother_of_god": "María, Madre de Dios (Octava de Navidad)",
        "epiphany": "La Epifanía",
        "baptism_of_lord": "El Bautismo del Señor",
        "ash_wednesday": "Miércoles de Ceniza",
        "palm_sunday": "Domingo de Ramos",
        "good_friday": "Viernes Santo",
        "holy_saturday": "Sábado Santo",
        "easter_sunday": "Domingo de Resurrección",
        "ascension": "La Ascensión",
        "pentecost": "Pentecostés",
        "holy_trinity": "Domingo de Trinidad",
        "corpus_christi": "Corpus Christi (Cuerpo y Sangre de Cristo)",
        "sacred_heart": "El Sagrado Corazón de Jesús",
        "mother_of_church": "María, Madre de la Iglesia",
        "immaculate_heart": "El Inmaculado Corazón de María",
        "christ_king": "Cristo Rey",
        "saturday_memorial_bvm": "The Memorial of the Blessed Virgin Mary on Saturday"
      },
      "extension": {
        "christ_eternal_priest": "Jesucristo, Sumo y Eterno Sacerdote"
      },
      "ordinary": {
        "sunday": "%{week} Domingo del Tiempo Ordinario",
        "ferial": "%{weekday}, %{week} semana del Tiempo Ordinario"
      },
      "advent": {
        "sunday": "%{week} Domingo de Adviento",
        "ferial": "%{weekday}, %{week} semana de Adviento",
        "before_christmas": "%{day} de Diciembre"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "%{day} día de la Octava de Navidad"
        },
        "sunday": "%{week} Sunday después de la Natividad del Señor",
        "ferial": "%{weekday} después de la Octava de Navidad",
        "after_epiphany": {
          "ferial": "%{weekday} después de la Epifanía"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} después del Miércoles de Ceniza"
        },
        "sunday": "%{week} Domingo de Cuaresma",
        "ferial": "%{weekday}, %{week} semana de Cuaresma",
        "holy_week": {
          "ferial": "%{weekday} de la Semana Santa"
        }
      },
      "easter": {
        "octave": {
          "ferial": "%{weekday} de Pascua"
        },
        "sunday": "%{week} Domingo de Pascua",
        "ferial": "%{weekday}, %{week} semana de Pascua"
      }
    },
    "rank": {
      "1_1": "Triduo Pascual",
      "1_2": "Días litúrgicos primarios",
      "1_3": "Solemnidades en el Calendario General",
      "1_4": "Solemnidades",
      "2_5": "Fiestas del Señor en el Calendario General",
      "2_6": "Unprivileged Sundays",
      "2_7": "Fiestas de Santos en el Calendario General",
      "2_8": "Fiestas",
      "2_9": "Días Privilegiados",
      "3_10": "Memorias Obligatorias en el Calendario General",
      "3_11": "Memorias Obligatorias",
      "3_12": "Memorias Opcionales",
      "3_13": "Días",
      "4_0": "Conmemoraciones",
      "short": {
        "solemnity": "solemnidad",
        "feast": "fiesta",
        "sunday": "Domingo",
        "memorial": "memoria",
        "memorial_opt": "memoria opcional",
        "ferial": "ferial",
        "commemoration": "conmemoración"
      }
    },
    "weekday": {
      "0": "Domingo",
      "1": "Lunes",
      "2": "Martes",
      "3": "Miércoles",
      "4": "Jueves",
      "5": "Viernes",
      "6": "Sábado"
    },
    "colour": {
      "violet": "violeta",
      "white": "blanco",
      "green": "verde",
      "red": "rojo"
    }
  },
  "fr": {
    "temporale": {
      "season": {
        "advent": "Temps de l'Avent",
        "christmas": "Temps de Noël",
        "lent": "Temps du Carême",
        "easter": "Temps de Pâques",
        "ordinary": "Temps ordinaire"
      },
      "solemnity": {
        "nativity": "La Nativité du Seigneur",
        "holy_family": "La Sainte Famille de Jésus, Marie et Joseph",
        "mother_of_god": "Octave de Noël, de Marie, Mère de Dieu",
        "epiphany": "L'Epiphanie du Seigneur",
        "baptism_of_lord": "Le Baptême du Seigneur",
        "ash_wednesday": "Mercredi des Cendres",
        "palm_sunday": "Dimanche des Rameaux de la Passion du Seigneur",
        "good_friday": "Vendredi de la Passion du Seigneur",
        "holy_saturday": "Samedi Saint",
        "easter_sunday": "Dimanche de Pâques de la Résurrection du Seigneur",
        "ascension": "Ascension du Seigneur",
        "pentecost": "Dimanche de Pentecôte",
        "holy_trinity": "La Très Sainte Trinité",
        "corpus_christi": "Le Très Saint Corps et Sang du Christ",
        "sacred_heart": "Le Sacré-Coeur de Jésus",
        "mother_of_church": "Sainte Marie, Mère de l’Eglise",
        "immaculate_heart": "Le Coeur Immaculé de Marie",
        "christ_king": "Notre Seigneur Jésus Christ, Roi de l'Univers",
        "saturday_memorial_bvm": "Mémoire de Sainte-Marie le samedi"
      },
      "extension": {
        "christ_eternal_priest": "Jésus Christ, prêtre éternel et souverain"
      },
      "ordinary": {
        "sunday": "%{week} Dimanche de Temps Ordinaire",
        "ferial": "%{weekday}, %{week} semaine de Temps Ordinaire"
      },
      "advent": {
        "sunday": "%{week} Dimanche de l'Avent",
        "ferial": "%{weekday}, %{week} semaine de L'Avent",
        "before_christmas": "%{day} décembre"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "Jour %{day} de l'Octave de Noël"
        },
        "sunday": "%{week} Dimanche après la Naissance du Seigneur",
        "ferial": "%{weekday} après l'Octave de Noël",
        "after_epiphany": {
          "ferial": "%{weekday} après l'Epiphanie"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} après le Mercredi des Cendres"
        },
        "sunday": "%{week} Dimanche de Carême",
        "ferial": "%{weekday}, %{week} semaine de Carême",
        "holy_week": {
          "ferial": "%{weekday} de la Semaine Sainte"
        }
      },
      "easter": {
        "octave": {
          "ferial": "Pâques %{weekday}"
        },
        "sunday": "%{week} Dimanche de Pâques",
        "ferial": "%{weekday}, %{week} semaine de Pâques"
      }
    },
    "rank": {
      "1_1": "Triduum Pascal",
      "1_2": "Jours liturgiques primaires",
      "1_3": "Solennités du Calendrier Général",
      "1_4": "Solennités appropriées",
      "2_5": "Fête du Seigneur du Calendrier Général",
      "2_6": "Dimanches du temps de Noël et les dimanches per annum",
      "2_7": "Fête des Saints du Calendrier Général",
      "2_8": "Fête appropriées",
      "2_9": "Jours fériés privilégiés",
      "3_10": "Mémoriaux obligatoire du Calendrier Général",
      "3_11": "Mémoriaux obligatoire appropriés",
      "3_12": "Mémoriaux optionnels",
      "3_13": "Fériés",
      "4_0": "Commémorations",
      "short": {
        "solemnity": "solennité",
        "feast": "fête",
        "sunday": "Dimanche",
        "memorial": "mémorial",
        "memorial_opt": "mémorial optionnel",
        "ferial": "férié",
        "commemoration": "commémoration"
      }
    },
    "weekday": {
      "0": "Dimanche",
      "1": "Lundi",
      "2": "Mardi",
      "3": "Mercredi",
      "4": "Jeudi",
      "5": "Vendredi",
      "6": "Samedi"
    },
    "colour": {
      "violet": "violet",
      "white": "blanc",
      "green": "vert",
      "red": "rouge"
    }
  },
  "it": {
    "temporale": {
      "season": {
        "advent": "Tempo di Avvento",
        "christmas": "Tempo di Natale",
        "lent": "Tempo di Quaresima",
        "easter": "Tempo pasquale",
        "ordinary": "Tempo ordinario"
      },
      "solemnity": {
        "nativity": "Natale del Signore",
        "holy_family": "Santa Famiglia di Gesù, Maria e Giuseppe",
        "mother_of_god": "Ottava di Natale. Maria Santissima Madre di Dio",
        "epiphany": "Epifania del Signore",
        "baptism_of_lord": "Battesimo del Signore",
        "ash_wednesday": "Mercoledì delle ceneri",
        "palm_sunday": "Domenica delle palme",
        "good_friday": "Venerdì santo",
        "holy_saturday": "Sabato santo",
        "easter_sunday": "Domenica di Resurrezione",
        "ascension": "Ascensione di Gesù",
        "pentecost": "Domenica Pentecoste",
        "holy_trinity": "Santissima Trinità",
        "corpus_christi": "Santissimo Corpo e Sangue di Cristo",
        "sacred_heart": "Sacro Cuore di Gesù",
        "mother_of_church": "Maria Madre della Chiesa",
        "immaculate_heart": "Cuore Immacolato di Maria",
        "christ_king": "Nostro Signore Gesù Cristo Re dell'universo",
        "saturday_memorial_bvm": "Memoria di santa Maria in sabato"
      },
      "extension": {
        "christ_eternal_priest": "Nostro Signore Gesù Cristo Sommo e Eterno Sacerdote"
      },
      "ordinary": {
        "sunday": "%{week} Domenica del Tempo Ordinario",
        "ferial": "%{weekday} della %{week} settimana del Tempo Ordinario"
      },
      "advent": {
        "sunday": "%{week} Domenica Avvento",
        "ferial": "%{weekday}, %{week} Avvento",
        "before_christmas": "%{day} dicembre"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "%{day}, Ottava di Natale"
        },
        "sunday": "Domenica %{week}, Tempo di Natale",
        "ferial": "%{weekday}, Tempo di Natale",
        "after_epiphany": {
          "ferial": "%{weekday} dopo la Epifania del Signore"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} dopo le Ceneri"
        },
        "sunday": "Domenica %{week} di Quaresima",
        "ferial": "%{weekday}, %{week} di Quaresima",
        "holy_week": {
          "ferial": "%{weekday}, Settimana Santa"
        }
      },
      "easter": {
        "octave": {
          "ferial": "%{weekday}, Ottava di Pasqua"
        },
        "sunday": "Domenica %{week} di Pasqua",
        "ferial": "%{weekday}, %{week} di Pasqua"
      }
    },
    "rank": {
      "1_1": "Easter triduum",
      "1_2": "Primary liturgical days",
      "1_3": "Solemnities in the General Calendar",
      "1_4": "Proper solemnities",
      "2_5": "Feasts of the Lord in the General Calendar",
      "2_6": "Unprivileged Sundays",
      "2_7": "Feasts of saints in the General Calendar",
      "2_8": "Proper feasts",
      "2_9": "Privileged ferials",
      "3_10": "Obligatory memorials in the General Calendar",
      "3_11": "Proper obligatory memorials",
      "3_12": "Optional memorials",
      "3_13": "Ferials",
      "4_0": "Commemorations",
      "short": {
        "solemnity": "solennità",
        "feast": "festa",
        "sunday": "domenica",
        "memorial": "memoria",
        "memorial_opt": "memoria facoltativa",
        "ferial": "feria",
        "commemoration": "commemorazione"
      }
    },
    "weekday": {
      "0": "Domenica",
      "1": "Lunedì",
      "2": "Martedì",
      "3": "Mercoledì",
      "4": "Giovedì",
      "5": "Venerdì",
      "6": "Sabato"
    },
    "colour": {
      "violet": "viola",
      "white": "bianco",
      "green": "verde",
      "red": "rosso"
    }
  },
  "la": {
    "temporale": {
      "season": {
        "advent": "Tempus Adventus",
        "christmas": "Tempus Nativitatis",
        "lent": "Tempus Quadragesimae",
        "easter": "Tempus Paschale",
        "ordinary": "Tempus per annum"
      },
      "solemnity": {
        "nativity": "In Nativitate Domini",
        "holy_family": "Sanctae Familiae Iesu, Mariae et Ioseph",
        "mother_of_god": "In Octava Nativitatis Domini, Sanctae Dei Genitricis Mariae",
        "epiphany": "In Epiphania Domini",
        "baptism_of_lord": "In Baptismate Domini",
        "ash_wednesday": "Feria IV Cinerum",
        "palm_sunday": "Dominica in Palmis de Passione Domini",
        "holy_thursday": "Feria V Hebdomadae Sanctae",
        "holy_thursday_evening": "Feria V in Cena Domini",
        "good_friday": "Feria VI in Passione Domini",
        "holy_saturday": "Sabbato sancto",
        "easter_sunday": "Dominica Paschae in Resurrectione Domini",
        "ascension": "In Ascensione Domini",
        "pentecost": "Dominica Pentecostes",
        "holy_trinity": "Sanctissimae Trinitatis",
        "corpus_christi": "Sanctissimi Corporis et Sanguinis Christi",
        "sacred_heart": "Sacratissimi Cordis Iesu",
        "mother_of_church": "B. Mariae Virginis Ecclesiae Matris",
        "immaculate_heart": "Immaculati Cordis B. Mariae Virginis",
        "christ_king": "Domini nostri Iesu Christi universorum regis",
        "saturday_memorial_bvm": "Memoria Sanctae Mariae in Sabbato"
      },
      "extension": {
        "christ_eternal_priest": "Domini nostri Iesu Christi Summi et Aeterni Sacerdotis"
      },
      "ordinary": {
        "sunday": "Dominica %{week} per annum",
        "ferial": "%{weekday}, hebdomada %{week} per annum"
      },
      "advent": {
        "sunday": "Dominica %{week} Adventus",
        "ferial": "%{weekday}, hebdomada %{week} Adventus",
        "before_christmas": "Die %{day} decembris"
      },
      "christmas": {
        "nativity_octave": {
          "ferial": "De die %{day} infra octavam Nativitatis"
        },
        "sunday": "Dominica %{week} post Nativitatem",
        "ferial": "%{weekday} post octavam Nativitatis",
        "after_epiphany": {
          "ferial": "%{weekday} post Epiphaniam"
        }
      },
      "lent": {
        "after_ashes": {
          "ferial": "%{weekday} post Cineres"
        },
        "sunday": "Dominica %{week} Quadragesimae",
        "ferial": "%{weekday}, hebdomada %{week} Quadragesimae",
        "holy_week": {
          "ferial": "%{weekday} Hebdomadae Sanctae"
        }
      },
      "easter": {
        "octave": {
          "ferial": "%{weekday} infra octavam Paschae"
        },
        "sunday": "Dominica %{week} Paschae",
        "ferial": "%{weekday}, hebdomada %{week} temporis paschalis"
      }
    },
    "rank": {
      "1_1": "Triduum paschale",
      "1_2": "Dies liturgici primarii",
      "1_3": "Sollemnitates in Calendario generali inscriptae",
      "1_4": "Sollemnitates propriae",
      "2_5": "Festa Domini in Calendario generali inscripta",
      "2_6": "Dominicae temporis Nativitatis et dominicae per annum",
      "2_7": "Festa sanctorum in Calendario generali inscripta",
      "2_8": "Festa propria",
      "2_9": "Feriae privilegiatae",
      "3_10": "Memoriae obligatoriae in Calendario generali inscriptae",
      "3_11": "Memoriae obligatoriae propriae",
      "3_12": "Memoriae ad libitum",
      "3_13": "Feriae",
      "4_0": "Commemorationes",
      "short": {
        "solemnity": "sollemnitas",
        "feast": "festum",
        "sunday": "dominica",
        "memorial": "memoria",
        "memorial_opt": "memoria ad libitum",
        "ferial": "feria",
        "commemoration": "commemoratio"
      }
    },
    "weekday": {
      "0": "Dominica",
      "1": "Feria secunda",
      "2": "Feria tertia",
      "3": "Feria quarta",
      "4": "Feria quinta",
      "5": "Feria sexta",
      "6": "Sabbato"
    },
    "colour": {
      "violet": "violaceus",
      "white": "albus",
      "green": "viridis",
      "red": "rubeus"
    }
  }
};
